combine_control_expr = false
fn_single_line = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 120
tab_spaces = 2
unstable_features = true
use_field_init_shorthand = true
