console_title_template = '{{ .Shell }} - {{ .Folder }}'
version = 3
shell_integration = true
final_space = true

[debug_prompt]
template = 'dbg '

[secondary_prompt]
template = '❯ '
foreground = 'darkGray'
background = 'transparent'

[transient_prompt]
template = '❯ '
background = 'transparent'
foreground_templates = [
  '{{if ne .Code 0}}red{{end}}',
  '{{if eq .Code 0}}green{{end}}',
]

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '<b>Administrator</b> <default>in</> '
foreground = 'red'
background = 'transparent'
type = 'root'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'

[[blocks.segments]]
template = '<b>{{ .Path }}</b>'
foreground = 'cyan'
background = 'transparent'
type = 'path'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
style = 'full'

[[blocks.segments]]
template = ' <default>on</> <b>{{ .HEAD }}</b> <b><red>[{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}]</></b>'
foreground = 'magenta'
background = 'transparent'
type = 'git'
style = 'plain'

[blocks.segments.properties]
branch_icon = ' '
cache_duration = 'none'
fetch_status = true

[[blocks.segments]]
template = ' <default>took</> <b>{{ .FormattedMs }}</b>'
foreground = 'yellow'
background = 'transparent'
type = 'executiontime'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
style = 'round'
threshold = 2000

[[blocks]]
type = 'prompt'
alignment = 'right'
overflow = 'hide'

[[blocks.segments]]
template = '  {{ .Full }}'
foreground = '#ff4d03'
background = 'transparent'
type = 'java'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'

[[blocks.segments]]
template = '  {{ .Full }}'
foreground = 'green'
background = 'transparent'
type = 'node'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'

[[blocks.segments]]
template = ' 🐍 {{ .Full }}'
foreground = 'yellow'
background = 'transparent'
type = 'python'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
display_default = false

[[blocks.segments]]
template = ' 🦀 {{ .Full }}'
foreground = 'red'
background = 'transparent'
type = 'rust'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '❯'
background = 'transparent'
type = 'text'
style = 'plain'
foreground_templates = [
  '{{if ne .Code 0}}red{{end}}',
  '{{if eq .Code 0}}green{{end}}',
]

[blocks.segments.properties]
cache_duration = 'none'
